item {
  id: 1
  name: 'valvula1'
}

item {
  id: 2
  name: 'valvula2'
}

item {
  id: 3
  name: 'valvula3'
}

item {
  id: 4
  name: 'valvula4'
}

item {
  id: 5
  name: 'valvula5'
}

item {
  id: 6
  name: 'valvula6'
}

item {
  id: 7
  name: 'valvula7'
}

item {
  id: 8
  name: 'valvula8'
}

